Completed Lesson 1
vdmppv-xbsoftware/webix-custom pull request #1
Opened 2022-04-14 12:11 UTC by vdmppv-xbsoftware

2022-04-14 14:09 UTC, fireFireee requested changes

2022-04-14 14:09 UTC, fireFireee commented on index.html
> +    <link rel="stylesheet" href="//cdn.webix.com/edge/webix.css" type="text/css">
а точно нужно два раза подключать css?

2022-04-14 14:09 UTC, fireFireee commented on src/script.js
> +  id: FORM_VIEW_ID,
не думаю, что это здесь нужно

2022-04-14 14:09 UTC, fireFireee commented on src/script.js
> +  name: BUTTON_VIEW_ID,
я бы не использовал айдишки для вьюшек для названия компонентов, будет выглядеть странно, если нам нужно будет добавить несколько таких вьюшек..

2022-04-14 14:09 UTC, fireFireee commented on src/script.js
> +    Object.keys(formValues).forEach(key => {
не ошибка, дело вкусов, но я бы воспользовался здесь Object.entries
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

2022-04-14 14:09 UTC, fireFireee commented on src/script.js
> +	          onStateChange(state){
форматирование немного поехало
возможно только здесь (на гитхабе), но проверь на всякий случай

2022-04-14 14:09 UTC, fireFireee commented on src/script.js
> +          state: 0,
а если прокинем другой значение, оно сразу нормально отрисуется/отработает?

2022-04-14 15:42 UTC, vdmppv-xbsoftware commented on index.html
> +    <link rel="stylesheet" href="//cdn.webix.com/edge/webix.css" type="text/css">
исправил

2022-04-14 15:42 UTC, vdmppv-xbsoftware commented on src/script.js
> +  id: FORM_VIEW_ID,
исправил

2022-04-14 15:43 UTC, vdmppv-xbsoftware commented on src/script.js
> +    Object.keys(formValues).forEach(key => {
исправил

2022-04-14 15:43 UTC, vdmppv-xbsoftware commented on src/script.js
> +	          onStateChange(state){
видимо только на гитхабе поехало, у меня всё ок

2022-04-14 16:46 UTC, fireFireee requested changes

2022-04-14 16:46 UTC, fireFireee commented on src/script.js
> +      $$("customForm").clear();
думаю здесь пользоваться айдишкой оч плохая идея:
а если мы создадим такую же формочку, но с другой айдишкой и не прокинем cancelAction?)

2022-04-14 16:47 UTC, fireFireee commented on src/script.js
> +    console.log(Object.entries(formValues));
?

2022-04-14 19:22 UTC, HelgaListopad commented on src/script.js
> +	          onStateChange(state){
Форматирование на разных платформах может поехать, если в отступах попадаются и табы, и пробелы.

На некоторых проектах на это будет ругаться линтер (и, вероятно, предлагать исправить), но в целом ты можешь настроить себе Prettier (или аналогичную вещь) - в том же VS Code c его помощью можно [отформатировать](https://www.digitalocean.com/community/tutorials/code-formatting-with-prettier-in-visual-studio-code#the-format-document-command) весь документ по одному стандарту.

2022-04-14 19:34 UTC, HelgaListopad requested changes

2022-04-14 19:34 UTC, HelgaListopad commented on src/script.js
> +    config.label = config.states[config.state];
Есть риск легко сломать.)
`config.states` должен быть массивом, нужна проверка
Если `config.state` undefined, нужно значение по умолчанию
Есть ещё варианты, но отсутствие/не тот формат ожидаемых свойств в конфигурации, пришедшей от юзера - самое основное

В целом выше по коду ты мог бы не просто выходить, если `config.states` нет, а делать ещё и такие проверки
И если не пришло нужных настроек, по умолчанию выставлять `states = [ "Default" ]`, а `state = 0`

2022-04-14 19:34 UTC, HelgaListopad commented on src/script.js
> +      if (currentState > 2) currentState = 0;
Проверяй тут `states.length`

2022-04-14 19:34 UTC, HelgaListopad commented on src/script.js
> +          click: config.cancelAction ? config.cancelAction : this.defaults.cancelAction
В такой записи `this` в cancelAction будет кнопкой, хотя это по идее обработчики всей формы
И если понадобится собрать значения с формы, придётся ещё до неё добираться.
Используй вызов на форму:
```js
click: () => config.method ? config.method.call(this) : this.defaults.method.call(this)
```

2022-04-14 22:04 UTC, HelgaListopad approved these changes

2022-04-14 22:15 UTC, fireFireee commented on src/script.js
> +      if (!config || !config.states || !config.state) {
если мы прокинем state: 0 в конфиг, будет ли работать как нужно?

2022-04-14 22:42 UTC, vdmppv-xbsoftware commented on src/script.js
> +      if (!config || !config.states || !config.state) {
исправил

2022-04-15 10:33 UTC, fireFireee commented on src/script.js
> +      if (!config || !config.states || config.state == undefined) {
не совсем

в таком случае, если мы прокинем states как положено и закинем в state допустим любое число отличное от 0,1,2 оно сломается

2022-04-15 10:33 UTC, fireFireee commented on src/script.js
> +      if (!config || !config.states || config.state == undefined) {
не совсем

в таком случае, если мы прокинем states как положено и закинем в state допустим любое число отличное от 0,1,2 оно сломается

2022-04-15 12:56 UTC, fireFireee requested changes

2022-04-15 12:56 UTC, fireFireee commented on src/script.js
> +      config.label = config.states[config.state];
если я прокину в states 2 значения, а в state прокину 2, что отрисуется?

2022-04-15 13:25 UTC, vdmppv-xbsoftware commented on src/script.js
> +      config.label = config.states[config.state];
исправил

2022-04-15 14:58 UTC, merged